# Generated by Django 5.2 on 2026-07-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='safety_rules',
        ),
        migrations.AddField(
            model_name='submission',
            name='safety_rule',
            field=models.CharField(choices=[('safe', 'Safe'), ('needs_review', 'Needs Review'), ('unsafe', 'Unsafe')], default='safe', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='classification_result',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
